repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.22 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: terraform-validate
    - id: terraform-fmt
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_tfsec
    - id: terraform_docs
      args:
        - '--args=--recursive'
        - '--args=--output-file=README.md'
        - '--args=--recursive-path=.'
    - id: terraform_checkov
      args:
        - --args=--skip-check CKV2_AZURE_21,CKV2_AZURE_32,CKV2_AZURE_33,CKV_AZURE_112,CKV_AZURE_59,CKV_AZURE_134,CKV_AZURE_98,CKV_AZURE_124,CKV_AZURE_209,CKV_AZURE_208,CKV_AZURE_207
    - id: terraform_tflint
      args:
      - '--args=--enable-rule=terraform_deprecated_interpolation'
      - '--args=--enable-rule=terraform_deprecated_index'
      - '--args=--enable-rule=terraform_unused_declarations'
      - '--args=--enable-rule=terraform_comment_syntax'
      - '--args=--enable-rule=terraform_documented_outputs'
      - '--args=--enable-rule=terraform_documented_variables'
      - '--args=--enable-rule=terraform_typed_variables'
      - '--args=--enable-rule=terraform_naming_convention'
      - '--args=--enable-rule=terraform_required_version'
      - '--args=--enable-rule=terraform_required_providers'
      - '--args=--enable-rule=terraform_unused_required_providers'
      - '--args=--enable-rule=terraform_standard_module_structure'