output "aad_application_id" {
  value       = azuread_application.aad_application.application_id
  description = <<-EOF
    Azure AD application id.

EOF
}

output "aad_aapplication_object_id" {
  value       = azuread_application.aad_application.object_id
  description = <<-EOF
    Azure AD application object id.

EOF
}

output "aad_application_client_secret_id" {
  value       = azuread_application_password.aad_application_password.key_id
  description = <<-EOF
    A UUID used to uniquely identify this password credential.

EOF
}

output "aad_application_client_secret_value" {
  value       = azuread_application_password.aad_application_password.value
  description = <<-EOF
    The secret value for this application, which is generated by Azure AD.

EOF
}